name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 3
  # workflow_dispatch:

# 4
jobs:
  # 5
  build:
    name: Build APK
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
#           cache: 'gradle'
         
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.8"
          channel: 'stable'
#           cache: true 
      - name: Change Directory
        run: cd smart_fueling
      # 12
      - name: Test and build apk
        run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk -t lib/main.dart --split-per-abi
      - name: Upload a Build Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: smart_fueling/build/app/outputs/apk/release/*.apk
          token: ${{ secrets.TOKEN }}


      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
